# Generated by Django 4.0.2 on 2022-02-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=255)),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
