# Generated by Django 4.0.2 on 2022-03-01 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecordModel',
            new_name='Record',
        ),
    ]
